name: extensions_playground
description: A playground for exploring extension concepts.

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  plugin: ^0.2.0
  inject:
    path: ../inject.dart/package/inject

dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0
  inject_generator:
    path: ../inject.dart/package/inject_generator
  pedantic: ^1.0.0
